name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: src
      
      - name: setup
        uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: humble

      - name: build
        run: |
          colcon build --symlink-install