name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution: [foxy, galactic, humble]
        include:
          - docker_image: ubuntu:focal
            ros_distribution: foxy
          - docker_image: ubuntu:focal
            ros_distribution: galactic
          - docker_image: ubuntu:jammy
            ros_distribution: humble
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: src
      
      - name: setup
        uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: build
        run: |
          colcon build --symlink-install